name: asdf
on: push

jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: superbrothers/kubectl-open-svc-plugin
    - uses: asdf-vm/actions/install@v1
      with:
        tool_versions: |
          golang 1.13.10
    - run: go env
    - run: make build
