name: asdf
on: push

jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: asdf setup
        uses: asdf-vm/actions/setup@v1.0.0
      - name: asdf install
        run: |
          set -x
          asdf plugin add aws-iam-authenticator https://github.com/stefansedich/asdf-aws-iam-authenticator
          asdf install
          asdf exec aws-iam-authenticator help
